# Imagen base con Python y Tkinter
FROM python:3.10-slim

# Instalar Tkinter y dependencias gráficas
RUN apt-get update && apt-get install -y python3-tk x11-apps && rm -rf /var/lib/apt/lists/*

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el código del cliente
COPY client.py .

# Configurar la variable DISPLAY para que se pueda abrir la interfaz gráfica
ENV DISPLAY=:0

# Comando para ejecutar el cliente
CMD ["python3", "client.py"]
